branch-defaults:
  default:
    environment: portfolio
    group_suffix: null
global:
  application_name: eb_portfolio
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
