import React from 'react';
import PDBContainer from '../pdbcontainer.js';
import LazyLoad from 'react-lazyload';

const wordcloud = require('../images/wordcloudforreddit.png')

const Projects = () => (
	<div className='projects'>
		<div className='project'>
			<h1>Word Cloud for reddit</h1>
			<LazyLoad height={200} once>
				<img src={wordcloud} className='projects--wordcloud' alt='A word cloud generated by Word Cloud for reddit'/>
			</LazyLoad>
			<p>Open-source ReactJS-based extension for Google Chrome to make beautiful word clouds from reddit searches. <a href='https://github.com/fairlight-excalibur'>Source</a></p>
		</div>
		<div className='project'>
			<h1>Wandering Souls</h1>
			<iframe
				className='projects--youtube'
				width="560"
				height="315"
				src="https://www.youtube-nocookie.com/embed/26rtXu-Ev9c?rel=0"
				frameBorder="0"
				allow="autoplay; encrypted-media"
				allowFullScreen
			/>
			<p>Augmented reality ghost-hunting game using geolocation - track ghosts in real time and view their obituaries. Available on iOS and Android. Written in C#/Unity, backend in PHP/SQL.</p>
		</div>
		<div className='project'>
			<h1>Modelling of P3 Protein</h1>
			<LazyLoad height={200} once>
				<PDBContainer/>
			</LazyLoad>
			<p>At Northeastern Illinois University, I worked on an interdisciplanary team of chemists, biologists, and coders. We used atomic force microscopy, scanning tunneling microscopy, and open source C++ tools to help develop a new methodology for visualizing protein structures.</p>
		</div>
	</div>
);

export default Projects;