import React, { Component } from 'react';
import PDBContainer from '../pdbcontainer.js';

const wordcloud = require('../images/wordcloudforreddit.png');
const youtubePreload = require('../images/youtubepreload.jpg');
const github = require('../images/github.png');

class Projects extends Component {
	constructor(props){
		super(props);
		this.state = {
			youtubeToggle: false
		}
	}

	toggle = () => {
		this.setState({youtubeToggle: !this.state.youtubeToggle});
	}

	render = () => {
		return (
			<div className='projects'>
				<div className='project content'>
					<h1>Word Cloud for reddit</h1>
						<img src={wordcloud} className='projects--wordcloud' alt='A word cloud generated by Word Cloud for reddit'/>
					<p><a href='https://github.com/LMNTL/word-cloud-for-reddit/'>Open-source</a> ReactJS-based extension for Google Chrome to make beautiful word clouds from reddit searches.</p>
				</div>
				<div className='project content'>
					<h1>Wandering Souls</h1>
					{ this.state.youtubeToggle ?
					<iframe
						className='projects--youtube'
						src="https://www.youtube-nocookie.com/embed/26rtXu-Ev9c?autoplay=1"
						frameBorder="0"
						allow="autoplay; encrypted-media"
						allowFullScreen
					/> :
						<img
							src={youtubePreload}
							className='projects--youtube'
							onClick={this.toggle}
						/> 
					}
					<p>Augmented reality ghost-hunting game using geolocation - track ghosts in real time and view their obituaries. Available on iOS and Android. Mobile client written in C#/Unity, backend in PHP(CodeReactor)/SQL.</p>
				</div>
				<div className='project content'>
					<h1>Nano-scale Microscopy and Modelling</h1>
					<div className='divider'>
						<PDBContainer
							alt='A visualization of the RpBph3 protein in its crystal structure. Coded using three.js.'
							className='divider--element'
						/>
					</div>
					<p>At <a href='https://neiu.edu/'>Northeastern Illinois University</a>, I worked on an interdisciplinary team of chemists, physicists, biologists, and coders. We used atomic force microscopy,
						scanning tunneling microscopy, and open source C++ tools to develop a new methodology for visualizing protein structures. You can watch and read some of that work
						in the <a href='https://www.jove.com/video/52164/atomic-force-microscopy-red-light-photoreceptors-using-peakforce'>Journal of Visualized Experiments</a> and the {' '}
						<a href='https://www.cambridge.org/core/journals/mrs-online-proceedings-library-archive/article/domain-structure-of-a-unique-bacterial-red-light-photoreceptor-as-revealed-by-atomic-force-microscopy/4BACFF1159092B39ED44F2EFCA713F67'>
						Proceedings of the Material Research Society.</a></p>
				</div>
			</div>
		)};
}
export default Projects;